.TH "include/affectation.h" 3 "Tue Apr 12 2016" "Projet-Cplusplus-IGM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/affectation.h \- La classe \fBAffectation\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'binaire\&.h'\fP
.br
\fC#include 'variable\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAffectation\fP"
.br
.RI "\fILa classe \fBAffectation\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
La classe \fBAffectation\fP\&. 


.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Projet-Cplusplus-IGM from the source code\&.
