.TH "src/binaire.cpp" 3 "Tue Apr 12 2016" "Projet-Cplusplus-IGM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/binaire.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'binaire\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBSomme\fP &a)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBDifference\fP &a)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBProduit\fP &a)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBDivision\fP &a)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBSuperieur\fP &a)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBInferieur\fP &a)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBSuperieurEgal\fP &a)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBInferieurEgal\fP &a)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & os, const \fBSomme\fP & a)"

.SS "ostream& operator<< (ostream & os, const \fBDifference\fP & a)"

.SS "ostream& operator<< (ostream & os, const \fBProduit\fP & a)"

.SS "ostream& operator<< (ostream & os, const \fBDivision\fP & a)"

.SS "ostream& operator<< (ostream & os, const \fBSuperieur\fP & a)"

.SS "ostream& operator<< (ostream & os, const \fBInferieur\fP & a)"

.SS "ostream& operator<< (ostream & os, const \fBSuperieurEgal\fP & a)"

.SS "ostream& operator<< (ostream & os, const \fBInferieurEgal\fP & a)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Projet-Cplusplus-IGM from the source code\&.
