.TH "include/binaire.h" 3 "Tue Apr 12 2016" "Projet-Cplusplus-IGM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/binaire.h \- La classe \fBBinaire\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'expression\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBinaire\fP"
.br
.RI "\fILa classe \fBBinaire\fP\&. \fP"
.ti -1c
.RI "class \fBSomme\fP"
.br
.RI "\fILa classe \fBSomme\fP\&. \fP"
.ti -1c
.RI "class \fBDifference\fP"
.br
.RI "\fILa classe \fBDifference\fP\&. \fP"
.ti -1c
.RI "class \fBProduit\fP"
.br
.RI "\fILa classe \fBProduit\fP\&. \fP"
.ti -1c
.RI "class \fBDivision\fP"
.br
.RI "\fILa classe \fBDivision\fP\&. \fP"
.ti -1c
.RI "class \fBSuperieur\fP"
.br
.RI "\fILa classe \fBSuperieur\fP\&. \fP"
.ti -1c
.RI "class \fBInferieur\fP"
.br
.RI "\fILa classe \fBInferieur\fP\&. \fP"
.ti -1c
.RI "class \fBSuperieurEgal\fP"
.br
.RI "\fILa classe \fBSuperieurEgal\fP\&. \fP"
.ti -1c
.RI "class \fBInferieurEgal\fP"
.br
.RI "\fILa classe \fBInferieurEgal\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
La classe \fBBinaire\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
TH 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Projet-Cplusplus-IGM from the source code\&.
