.TH "src/boucle.cpp" 3 "Tue Apr 12 2016" "Projet-Cplusplus-IGM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/boucle.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'boucle\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBPour\fP &pour)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & os, const \fBPour\fP & pour)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Projet-Cplusplus-IGM from the source code\&.
