.TH "Inferieur" 3 "Tue Apr 12 2016" "Projet-Cplusplus-IGM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inferieur \- La classe \fBInferieur\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <binaire\&.h>\fP
.PP
Inherits \fBBinaire\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInferieur\fP ()"
.br
.RI "\fIConstructeur\&. \fP"
.ti -1c
.RI "virtual \fB~Inferieur\fP ()"
.br
.RI "\fIDestructeur Destructeur de la classe \fBInferieur\fP\&. \fP"
.ti -1c
.RI "double \fBeval\fP () const "
.br
.RI "\fIEvalue l'expression Methode qui permet d'evaluer l'expression\&. \fP"
.ti -1c
.RI "\fBExpression\fP * \fBderiver\fP (const string &)"
.br
.RI "\fIDerive l'expression* Methode qui permet deriver l'expression\&. \fP"
.ti -1c
.RI "\fBExpression\fP * \fBsimplifier\fP ()"
.br
.RI "\fISimplifie l'expression Methode qui permet de simplifier l'expression\&. \fP"
.ti -1c
.RI "\fBExpression\fP * \fBclone\fP () const "
.br
.RI "\fIclone l'expression Methode qui permet de cloner l'expression \fP"
.ti -1c
.RI "string \fBafficher\fP () const "
.br
.RI "\fIAffiche l'expression Methode qui permet d'afficher l'expression\&. \fP"
.ti -1c
.RI "\fBInferieur\fP (\fBExpression\fP *, \fBExpression\fP *)"
.br
.RI "\fIConstructeur\&. \fP"
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &, const \fBInferieur\fP &)"
.br
.RI "\fIoperator<< Methode qui permet d'afficher l'expression \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
La classe \fBInferieur\fP\&. 

Cette classe représente les opérateurs de comparaison strictement inferieur 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Inferieur::Inferieur ()"

.PP
Constructeur\&. Constructeur de la classe \fBInferieur\fP 
.SS "Inferieur::~Inferieur ()\fC [virtual]\fP"

.PP
Destructeur Destructeur de la classe \fBInferieur\fP\&. 
.SS "Inferieur::Inferieur (\fBExpression\fP * exp1, \fBExpression\fP * exp2)"

.PP
Constructeur\&. Constructeur de la classe \fBInferieur\fP
.PP
\fBParameters:\fP
.RS 4
\fIexp1\fP : opérande gauche 
.br
\fIexp2\fP : opérande droite 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "string Inferieur::afficher () const\fC [virtual]\fP"

.PP
Affiche l'expression Methode qui permet d'afficher l'expression\&. 
.PP
\fBReturns:\fP
.RS 4
Le string d'expression 
.RE
.PP

.PP
Reimplemented from \fBExpression\fP\&.
.SS "\fBExpression\fP * Inferieur::clone () const\fC [virtual]\fP"

.PP
clone l'expression Methode qui permet de cloner l'expression 
.PP
\fBReturns:\fP
.RS 4
L'expression cloné 
.RE
.PP

.PP
Implements \fBExpression\fP\&.
.SS "\fBExpression\fP * Inferieur::deriver (const string & var)\fC [virtual]\fP"

.PP
Derive l'expression* Methode qui permet deriver l'expression\&. 
.PP
\fBReturns:\fP
.RS 4
L'expression derivé 
.RE
.PP

.PP
Implements \fBExpression\fP\&.
.SS "double Inferieur::eval () const\fC [virtual]\fP"

.PP
Evalue l'expression Methode qui permet d'evaluer l'expression\&. 
.PP
\fBReturns:\fP
.RS 4
Le valeur d'expression 
.RE
.PP

.PP
Implements \fBExpression\fP\&.
.SS "\fBExpression\fP * Inferieur::simplifier ()\fC [virtual]\fP"

.PP
Simplifie l'expression Methode qui permet de simplifier l'expression\&. 
.PP
\fBReturns:\fP
.RS 4
L'expression simplifié 
.RE
.PP

.PP
Implements \fBExpression\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & os, const \fBInferieur\fP & a)\fC [friend]\fP"

.PP
operator<< Methode qui permet d'afficher l'expression 

.SH "Author"
.PP 
Generated automatically by Doxygen for Projet-Cplusplus-IGM from the source code\&.
