.TH "Pour" 3 "Tue Apr 12 2016" "Projet-Cplusplus-IGM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pour \- La classe \fBPour\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <boucle\&.h>\fP
.PP
Inherits \fBExpression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPour\fP ()"
.br
.RI "\fIConstructeur\&. \fP"
.ti -1c
.RI "virtual \fB~Pour\fP ()"
.br
.RI "\fIDestructeur Destructeur de la classe \fBAffectation\fP\&. \fP"
.ti -1c
.RI "\fBPour\fP (\fBExpression\fP *init, \fBExpression\fP *cond, \fBExpression\fP *inc, \fBExpression\fP *calc)"
.br
.RI "\fIConstructeur\&. \fP"
.ti -1c
.RI "\fBExpression\fP * \fBclone\fP () const "
.br
.RI "\fIclone l'expression Methode qui permet de cloner l'expression \fP"
.ti -1c
.RI "string \fBafficher\fP () const "
.br
.RI "\fIAffiche l'expression Methode qui permet d'afficher l'expression\&. \fP"
.ti -1c
.RI "double \fBeval\fP () const "
.br
.RI "\fIEvalue l'expression Methode qui permet d'evaluer l'expression\&. \fP"
.ti -1c
.RI "\fBExpression\fP * \fBderiver\fP (const string &)"
.br
.RI "\fIDerive l'expression* Methode qui permet deriver l'expression\&. \fP"
.ti -1c
.RI "\fBExpression\fP * \fBsimplifier\fP ()"
.br
.RI "\fISimplifie l'expression Methode qui permet de simplifier l'expression\&. \fP"
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBPour\fP &)"
.br
.RI "\fIoperator<< Methode qui permet d'afficher l'expression \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
La classe \fBPour\fP\&. 

Cette classe représente les structures itératives\&. Elles permettent de réaliser des boucles\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Pour::Pour ()"

.PP
Constructeur\&. Constructeur de la classe \fBPour\fP 
.SS "Pour::~Pour ()\fC [virtual]\fP"

.PP
Destructeur Destructeur de la classe \fBAffectation\fP\&. 
.SS "Pour::Pour (\fBExpression\fP * init, \fBExpression\fP * cond, \fBExpression\fP * inc, \fBExpression\fP * calc)"

.PP
Constructeur\&. Constructeur de la classe \fBPour\fP 
.PP
\fBParameters:\fP
.RS 4
\fIinit\fP : l'initialisation 
.br
\fIcond\fP : le condition 
.br
\fIincr\fP : l'incrementaion 
.br
\fIcalcul\fP : le calcul 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "string Pour::afficher () const\fC [virtual]\fP"

.PP
Affiche l'expression Methode qui permet d'afficher l'expression\&. 
.PP
\fBReturns:\fP
.RS 4
Le string d'expression 
.RE
.PP

.PP
Reimplemented from \fBExpression\fP\&.
.SS "\fBExpression\fP * Pour::clone () const\fC [virtual]\fP"

.PP
clone l'expression Methode qui permet de cloner l'expression 
.PP
\fBReturns:\fP
.RS 4
L'expression cloné 
.RE
.PP

.PP
Implements \fBExpression\fP\&.
.SS "\fBExpression\fP * Pour::deriver (const string & var)\fC [virtual]\fP"

.PP
Derive l'expression* Methode qui permet deriver l'expression\&. 
.PP
\fBReturns:\fP
.RS 4
L'expression derivé 
.RE
.PP

.PP
Implements \fBExpression\fP\&.
.SS "double Pour::eval () const\fC [virtual]\fP"

.PP
Evalue l'expression Methode qui permet d'evaluer l'expression\&. 
.PP
\fBReturns:\fP
.RS 4
Le valeur d'expression 
.RE
.PP

.PP
Implements \fBExpression\fP\&.
.SS "\fBExpression\fP * Pour::simplifier ()\fC [virtual]\fP"

.PP
Simplifie l'expression Methode qui permet de simplifier l'expression\&. 
.PP
\fBReturns:\fP
.RS 4
L'expression simplifié 
.RE
.PP

.PP
Implements \fBExpression\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & os, const \fBPour\fP & pour)\fC [friend]\fP"

.PP
operator<< Methode qui permet d'afficher l'expression 

.SH "Author"
.PP 
Generated automatically by Doxygen for Projet-Cplusplus-IGM from the source code\&.
