#IFNDEF SERVEUR_H
#DEFINE SERVEUR_H

#DEFINE DLG_MAIN        500
#DEFINE DLG_CONNECT     501
#DEFINE DLG_LISTEN      502

#DEFINE ID_EDIT_DATA    600
#DEFINE ID_EDIT_SEND    601
#DEFINE ID_EDIT_HOST    602
#DEFINE ID_EDIT_PORT    603

#DEFINE ID_BTN_CONNECT  700
#DEFINE ID_BTN_CLEAR    701
#DEFINE ID_BTN_SEND     702
#DEFINE ID_BTN_GO       703
#DEFINE ID_BTN_LISTEN   704

#DEFINE ID_STATUS_MAIN  800

#DEFINE CUSTOM_NOTIFICATION     1045

#ENDIF // SERVEUR_H
